[package]
name = "trollcase-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
gtk = "0.18.1"
glib = "0.18.2"
